baseURL = 'http://knml.edu.pl/'
languageCode = 'pl-PL'
title = 'Koło Naukowe Machine Learning Politechniki Rzeszowskiej'
theme = 'hugo-profile'

enableRobotsTXT = true

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML", "RSS"]

[markup.goldmark.renderer]
    unsafe = true

[[Menus.main]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog"
    weight = 1

[[Menus.main]]
    identifier = "wiki"
    name = "Wiki"
    title = "Wiki"
    url = "https://wiki.knml.edu.pl"
    weight = 1

[[Menus.main]]
    identifier = "ML Summit"
    name = "ML Summit"
    title = "ML Summit"
    url = "/page/ml-summit"
    weight = 1

[params]
    title = "Koło Naukowe Machine Learning Politechniki Rzeszowskiej"
    description = "Strona główna Koła Naukowego Machine Learning"
    favicon = "/fav.png"
    useBootstrapCDN = false
    animate = true
    
[params.theme]
    defaultTheme = "light"
    disableThemeToggle = true

[params.font]
    fontSize = "1rem"
    fontWeight = 400
    lineHeight = 1.5
    textAlign = "left"

[params.navbar]
    align = "ms-auto"
    brandName = "KNML"
    disableSearch = true

[params.navbar.menus]
    disableAbout = false
    disableExperience = true
    disableEducation = true
    disableProjects = false
    disableAchievements = false
    disableContact = false

[params.hero]
    enable = true
    intro = "Cześć, jesteś na stronie głównej"
    title = "Koła naukowego Machine Learning"
    subtitle = "Politechniki Rzeszowskiej"
    content = "Wykorzystujemy uczenie maszynowe do rozwiązywania niecodziennych problemów. Zapraszamy do współpracy!"
    image = "logo_minified.svg"

[params.hero.bottomImage]
    enable = false

[params.hero.button]
    enable = true
    name = "Linktree"
    url = "https://linktr.ee/knml.prz"
    download = false
    newPage = true

[[params.hero.socialLinks.fontAwesomeIcons]]
    icon = "fab fa-github"
    url = "https://github.com/knmlprz"

[[params.hero.socialLinks.fontAwesomeIcons]]
    icon = "fab fa-facebook"
    url = "https://www.facebook.com/knmlprz"


[params.about]
    enable = true
    title = "O nas"
    image = "/images/profile.jpeg"
    content = """
Jesteśmy grupą studentów zafascynowanych analizą danych, uczeniem maszynowym
i sieciami neuronowymi. W naszym zespole są głównie studenci Inżynierii i
analizy danych, jednak każdy jest mile widziany.

Naszym celem jest rozwijanie umiejętności w zakresie uczenia maszynowego,
a także wykorzystanie ich w praktyce. W tym celu uczestniczymy w konkursach
i hackatonach, a także organizujemy własne wydarzenia.

Jeśli jesteś zainteresowany, dołącz do nas na naszym Discordzie!
"""

[params.achievements]
    enable = true
    title = "Nasze osiągnięcia"

[[params.achievements.items]]
    title = "II miejsce na BITEHack 2022 | AI"
    content = "Wykrywanie negatywnych emocji w sieci; drugie miejsce na BITEHack 2022 w kategorii AI"
    url = "https://w.prz.edu.pl/uczelnia/aktualnosci/sukces-studentow-kola-naukowego-machine-learning-2131.html"

[[params.achievements.items]]
    title = "Wyróżnienie na BITEHack 2023 | AI"
    content = "Analiza zużycia energii w budynkach; wyróżnienie na BITEHack 2023 w kategorii AI"
    url = "https://wmifs.prz.edu.pl/aktualnosci/wyroznienie-dla-kola-naukowego-machine-learning-381.html"

[[params.achievements.items]]
    title = "Nagroda w KoKoN 2022 | Cyfryzacja"
    content = "LARKFiD (Open Gov Data oraz stworzenie innowacyjnych aplikacji z wykorzystaniem technologii GPU)"
    url = "https://wmifs.prz.edu.pl/aktualnosci/pierwsza-nagroda-dla-kola-naukowego-machine-learning-363.html"

[[params.achievements.items]]
    title = "Wyróżnienie w StRuNa 2021"
    content = "Debiut Roku"
    url = "https://wmifs.prz.edu.pl/aktualnosci/kolo-naukowe-machine-learning-wyroznione-w-kategorii-debiut-roku-2021-298.html"

[params.projects.items.featured]
    name = "Repozytorium"
    link = "https://github.com/knmlprz/BITEHack"


[params.contact]
    title = "Kontakt"
    enable = true
    content = "Jeśli masz jakieś pytania/propozycje, napisz do nas maila!"
    email = "contact.knml.prz@gmail.com"
    btnName = "Napisz do nas"

[params.footer.recentPosts]
    enable = false

[params.footer.socialNetworks]
    github = "https://github.com/knmlprz"
    linkedin = "https://www.linkedin.com/company/knmlprz/"
    instagram = "https://www.instagram.com/knml.prz/"
    facebook = "https://www.facebook.com/knmlprz"

[params.listPages]
    disableFeaturedImage = false

[params.singlePages.readTime]
    enable = false
    content = "min read"

[params.singlePages.scrollprogress]
    enable = true

[params.terms]
    read = "Read"
    toc = "Spis treści"
    copyright = "All rights reserved"
    pageNotFound = "Page not found"
    emailText = "Check out this site"

[params.datesFormat]
    article = "Jan 2, 2006"
    articleList = "Jan 2, 2006"
    articleRecent = "Jan 2, 2006"
